binary_sensor:

  - platform: gpio

    pin:
      number: GPIO42
      mode:
        input: true
        pullup: true
      inverted: true

    name: Function Button

    on_press:

      then:

        - logger.log: "Button Pressed"

        - light.turn_on:

            id: rgb_status

            green: 100%

    on_release:

      then:

        - light.turn_off: rgb_status
