substitutions:
  name: ai-pi-lite
  friendly_name: AI Pi Lite

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

packages:
  wifi: !include packages/wifi.yaml
  logger: !include packages/logger.yaml
  led: !include packages/led.yaml
  button: !include packages/button.yaml
  display: !include packages/display.yaml
